kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "expr"
  namespace: "dev"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "expr"
  template:
    metadata:
      labels:
        app: "expr"
      annotations:
        tagrandom: "20220824214539"
    spec:
      volumes:
        - name: "expr"
          configMap:
            name: "expr"
            items:
              - key: "application.yml"
                path: "application.yml"
            defaultMode: 420
        - name: "expr_log"
          hostPath:
            path: "/logs/"
            type: "Directory"
      containers:
        - name: "expr"
          image: "expr:v1"
          env:
            - name: "TZ"
              value: "Asia/Shanghai"
          resources:
            limits:
              cpu: "4"
              memory: "3000Mi"
            requests:
              cpu: "500m"
              memory: "1000Mi"
          volumeMounts:
            - name: "expr"
              readOnly: true
              mountPath: "/config"
            - name: "expr_log"
              mountPath: "/var/log/expr"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: "File"
          imagePullPolicy: "Always"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      dnsPolicy: "ClusterFirst"
      securityContext: {}
      schedulerName: "default-scheduler"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
